# Generated by Buildr 1.4.0, change to your liking
# Standard maven2 repository
repositories.remote << 'http://www.ibiblio.org/maven2'
# Version number for this release
VERSION_NUMBER = `git describe --tags`.strip

desc 'Log4J Appender for MongoDB'
define 'log4mongo-java' do
  project.group = 'com.google.code'
  project.version = VERSION_NUMBER
  compile.with 'log4j:log4j:jar:1.2.16', 'org.mongodb:mongo-java-driver:jar:2.1'
  compile.with 'junit:junit:jar:4.7', 'log4j:log4j:jar:1.2.16', 'org.mongodb:mongo-java-driver:jar:2.1'
  package :jar, :id => 'log4mongo-java'
end
