# Generated by Buildr 1.4.0, change to your liking
# Standard maven2 repository
repositories.remote << 'http://www.ibiblio.org/maven2'

desc 'Log4J Appender for MongoDB'
define 'log4mongo-java' do
  project.group = 'com.google.code'
  project.version = '0.3'
  compile.with 'log4j:log4j:jar:1.2.15', 'org.mongodb:mongo-java-driver:jar:1.4'
  compile.with 'junit:junit:jar:4.7', 'log4j:log4j:jar:1.2.15', 'org.mongodb:mongo-java-driver:jar:1.4'
  package :jar, :id => 'log4mongo-java'
end
